# fly.toml app configuration file
app = "codebase-indexing"
primary_region = "dfw"

# Build configuration
[build]
  dockerfile = "Dockerfile"

# Environment variables
[env]
  NODE_ENV = "production"
  PORT = "3001"

# HTTP service configuration
[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  # HTTP options for SSE connections
  [services.http_options]
    compress = false  # Disable compression for SSE
    response.headers = { "X-Frame-Options" = "DENY", "Cache-Control" = "no-cache" }

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# Auto-scaling configuration
[vm]
  # Dedicated performance plan with 2 vCPUs and 4 GB RAM (minimum required)
  size = "performance-2x"
  # Explicitly set resources for clarity (Fly derives these from size, but it's good to be explicit)
  memory_mb = 4096
  cpus = 2
  cpu_kind = "performance"

# Ensure single instance for session affinity (MCP SSE requirement)
[autoscaler]
  enabled = true
  min_count = 1     # Keep 1 instance always running for SSE connections
  max_count = 1     # Single instance to ensure session consistency

# Metrics and monitoring
[metrics]
  port = 9091
  path = "/metrics"

# Secrets (you'll need to set these via flyctl)
# flyctl secrets set VOYAGE_API_KEY=your_key_here
# flyctl secrets set QDRANT_API_KEY=your_key_here
# flyctl secrets set QDRANT_URL=your_url_here 