# fly.toml app configuration file
app = "codebase-indexing"
primary_region = "dfw"

# Build configuration
[build]
  dockerfile = "Dockerfile"

# Environment variables
[env]
  NODE_ENV = "production"
  PORT = "3001"

# HTTP service configuration
[[services]]
  protocol = "tcp"
  internal_port = 3001
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["http", "tls"]

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    restart_limit = 0
    method = "get"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false

# Auto-scaling configuration
[vm]
  # Dedicated performance plan with 2 vCPUs and 2 GB RAM
  size = "performance-2x"
  # Explicitly set resources for clarity (Fly derives these from size, but it's good to be explicit)
  memory_mb = 2048
  cpus = 2
  cpu_kind = "performance"

# Horizontal autoscaling – spin up to 3 additional stateless machines on demand
[autoscaler]
  enabled = true
  min_count = 0     # Allow scale-to-zero when idle
  max_count = 3     # Burst up to 3 running machines during load

# Metrics and monitoring
[metrics]
  port = 9091
  path = "/metrics"

# Secrets (you'll need to set these via flyctl)
# flyctl secrets set VOYAGE_API_KEY=your_key_here
# flyctl secrets set QDRANT_API_KEY=your_key_here
# flyctl secrets set QDRANT_URL=your_url_here 